---
title: "ST 695 Split Plot Designs Whole Plot Model"
output: word_document
date: "2025-06-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This code chunk produces a design matrix for a design given the number of HTC Factors (HTC) and replicates for HTC Factors. The model of interest here is for Whole Plot Factors only and is given by

$y_{ij}^{W} = \beta_0 + \sum_{p=1}^{w}\beta_p x_{pi} + e_i^{W} + e_{ij}^{WS}$

```{r }

HTC <- 2
r <- 2

# Create the factors for the Design Matrix
w_names <- paste0("w", 1:HTC)

#Create list of whole plot variables
wpf_terms <- setNames(replicate(HTC, c(-1,1), simplify = FALSE), w_names)


# Create data frame of all combinations of w
df <- expand.grid(wpf_terms) #base experimental design
df_rep <- df[rep(seq_len(nrow(df)), r), ] #replicated experimental design
row.names(df_rep) <- NULL #make the row count sequential

# Build the formula for linear and interaction terms (no quadratic)
linear_terms <- w_names

fo <- as.formula(
  paste("~ (", paste(w_names, collapse = " + "), ")^2")
)

# Create the model matrix
X <- model.matrix(fo, data = df_rep)
colnames(X)[1] <- '0'

```

This code chunk generates a model of the Whole Plot Factors only.
```{r}

  fixed_effect_names <- paste0("beta", colnames(X))
  effects <- c(10,2.5,-1,1.5)
  beta <- setNames(effects, fixed_effect_names)  #assign values to fixed effect names
  
  sigma2_S <- 1
  sigma2_W <- 1
  
  mu <- X %*% beta
  n_groups <- 2^HTC
  
  delta <- rnorm(n_groups, mean = 0, sd = sqrt(sigma2_W))
  delta <- rep(delta, times = HTC)
  
  epsilon <- rnorm(nrow(X), mean = 0, sd = sqrt(sigma2_S))
  
  Y <- mu + delta + epsilon
  
  df <- data.frame(delta, df_rep, Y)
  
  fo <- as.formula(
  paste("Y ~ (", paste(linear_terms, collapse = " + "), ")^2"))
  
  rmodel_WPF <- lm(fo, data = df)
  summary(rmodel_WPF)


```
